apiVersion: v1
kind: Service
metadata:
  name: kube-summary-exporter
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: kube-summary-exporter
  ports:
  - name: http
    port: 9779
    targetPort: 9779
